wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1681266669.905401
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.10
      5: 0.14.2
      8:
      - 1
      - 4
      - 5
